;zend_extension=/opt/php/php-src/modules/opcache.so

date.timezone = "Europe/Paris"
session.auto_start = Off
short_open_tag = Off

memory_limit = 1G

opcache.enable = 1
opcache.enable_cli = 1
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256
realpath_cache_size = 4096K
realpath_cache_ttl = 600
opcache.jit_buffer_size=128M
opcache.jit=tracing

apc.enabled = 1
apc.enable_cli = 1

variables_order = "EGPCS"

; TODO: Change for production
error_reporting = E_ALL
display_errors = On

zend.assertions = 0
